### ISSUE TITLE
Hello, where is the relations.txt? Thanks very much.

### ISSUE THREAD

**Issue by xcgfth** [morningmoni/TaxoRL#1]

**Comment by xcgfth** [comment]
Can you open all the data  used in your project? Thanks very much.

**Comment by morningmoni** [comment]
Sorry, I forgot to put them there. They were actually used for hypernymy detection earlier and for taxonomy induction, there are only two relations (whether it is an edge or not). Other data should be in the pickle files.

**Comment by xcgfth** [comment]
Can you upload them again, Thanks very much.

**Comment by morningmoni** [comment]
I have already uploaded them. Please take a look.

**Comment by xcgfth** [comment]
I'm very grateful to you... Thanks..
