### ISSUE TITLE
Ferequency files

### ISSUE THREAD

**Issue by l6chen** [morningmoni/TaxoRL#10]
I am applying your method to my own dataset, so I need to generate my own frequency files.
How do you generate the twodatasets_freq_w.pkl & other frequency files?

**Comment by morningmoni** [comment]
We used the frequency counts from TAXI.
https://github.com/uhh-lt/taxi
TAXI at SemEval-2016 Task 13: a Taxonomy Induction Method based on Lexico-Syntactic Patterns, Substrings and Focused Crawling
