### ISSUE TITLE
Wordnet subtrees Visualization

### ISSUE THREAD

**Issue by xcgfth** [morningmoni/TaxoRL#2]
Hey, How to visualize the wordnet subtrees, what tools did you use ? Thanks!

**Comment by morningmoni** [comment]
d3.js
code can be found at https://github.com/morningmoni/wordnet-vis

**Comment by l6chen** [comment]
I have run the Sem-2016 evalution, and  I can draw the tree right now but how can I get the sample_taxonomy.txt as in the repo above? Is the T.save_for_vis deprecated ?
```
        T.draw()
        # T.save_for_vis(i_episode)
        pickle.dump(T, open('{}.tree.pkl'.format(T.filename), 'wb'))
```
