### ISSUE TITLE
corpus

### ISSUE THREAD

**Issue by xcgfth** [morningmoni/TaxoRL#3]
Hello, morningmoni, does the datasets in corpus need to create with ourselves? or can you open this datasets? Thank you very much.

**Comment by morningmoni** [comment]
I think I have attached the datasets in the datasets/ folder.

**Comment by xcgfth** [comment]
The datasets in corpus are used in knowledge_resource.py, like _term_to_id.db, _id_to_term.db, path_to_id.db, _id_to_path.db, _l2r.db  etc. I know from your source code these db files are created by yourself. However, I can’t understand what input is in the shell file  in the corpus folder. For example, the parameters like $1, $2, $3, $4 are input from the command line, but I don’t What files do these parameters represent?  I will be grateful you if you can provide your created db file. Thanks very much.
