### ISSUE TITLE
corpus

### ISSUE THREAD

**Issue by xcgfth** [morningmoni/TaxoRL#4]
The datasets in corpus are used in knowledge_resource.py, like _term_to_id.db, _id_to_term.db, path_to_id.db, _id_to_path.db, _l2r.db  etc. I know from your source code these db files are created by yourself. However, I can’t understand what input is in the shell file  in the corpus folder. For example, the parameters like $1, $2, $3, $4 are input from the command line, but I don’t What files do these parameters represent?  I will be grateful you if you can provide your created db file. Thanks very much.

**Comment by morningmoni** [comment]
I believe if you use the pickle files, those *.db are not needed, thanks.

**Comment by xcgfth** [comment]
The KnowledgeResource.py is called by the main in your train_RL.py, and this call  is necessary accrording from your code .  What's more, these db files are used in your KnowledgeResorce.py. Therefore, I want your db processed files. Thanks.

**Comment by xcgfth** [comment]
I have upgraded your corpus code from py2 to py3, and I have downloaded the lastest wikipedia dump file.  But I found I have no sufficient memory to process it when I extracted this xml file, of which size is 64G. So,  I  look forward to your further instuction. Thank you very much.

**Comment by xcgfth** [comment]
I basically figured out your code, and I seem to understand your meaning. The following two lines of code should be put into _if_ condition module if you don't use the db* files. 
......
 print 'Loading the corpus...', args.corpus_prefix, '*' * 10
    corpus = KnowledgeResource(args.corpus_prefix)

    if not os.path.exists('pickled_data/preload_data_{}_debug{}.pkl'.format(args.model_prefix_file, args.debug)):
        print 'Loading the vocabulary...'


......

**Comment by morningmoni** [comment]
Sorry for the late response. It indeed needs a lot of memory if you want to process it from scratch.
