### ISSUE TITLE
pickled_data missing

### ISSUE THREAD

**Issue by nowuoufu** [morningmoni/TaxoRL#5]
Hi, 
Is there any place to download "pickled_data/lower2original.pkl" data mentioned in the utils_common.py file.

**Comment by morningmoni** [comment]
Hi,
I think if you use the pickle files I provided, you don't need to generate features as you were trying to do. If you are using your own dataset, as the name lower2orignal suggests, it is just a dictionary that maps str.lower() -> original str. You can generate it yourself. It is only useful for the Capitalization feature.
