### ISSUE TITLE
Use the saved model for inference on a new set of terms

### ISSUE THREAD

**Issue by alkidi** [morningmoni/TaxoRL#6]
Hi, 
i builded everything from scratch for Italian language, ran the train_RL.py using the italian version of SemEval-2016 datasets for training, validation and test and saved the model. I can't figure out how to use the saved model for taxonomy induction on my own vocabulary. Thanks.

**Comment by morningmoni** [comment]
Can you provide more details? What are the errors that you are seeing?

**Comment by alkidi** [comment]
Thank you for the quick reply! There are no errors, i managed to create and save the model using the italian version of your dataset. I just don't know how to integrate my own set of terms(different from the terms contained in the dataset) in the process. So my question is: once i have the model, how can i pass to the model a set of terms in input for taxonomy induction out of these terms?

**Comment by morningmoni** [comment]
I am a bit confused. If you managed to train a model using the Italian version of the dataset, can you not replace its test set with your new set of terms? (I assumed that you went through the whole pipeline of feature generation)

**Comment by alkidi** [comment]
Yes, you are right, i went through the whole pipeline of feature generation. I will follow your advice and replace the test set with my set of terms. Thanks.
