### ISSUE TITLE
How to train with GPU

### ISSUE THREAD

**Issue by l6chen** [morningmoni/TaxoRL#7]
It seems the model_RL.py is based on cpu training? How could I train with GPU?
I commented ```dyparams.set_cpu_mode()``` and add the follow codes before import _dynet
```
import dynet_config
# Declare GPU as the default device type
dynet_config.set_gpu()
```
But the training speed is still slow. Please correct me if I do it wrong.

**Comment by morningmoni** [comment]
Yes you are right. When I tried GPU training, the speed was almost the same as CPU. Not sure if the issue was on my end or dynet's. Let me know if you find a solution :)

**Comment by l6chen** [comment]
Thanks for your quick reply. I trained on CPU with 40min per epoch(along with testing). It appears that you set the num of epoch as 1000. Is it necessary to train so many epochs to reach desirable results?

**Comment by morningmoni** [comment]
Normally, it isn't. I suggest you run it overnight and you can probably see the desired results next morning :)

**Comment by IS5882** [comment]
When I am training using GPU (google colab) each epoch is taking 20 mins, so 1000 epochs will need 14 days 😮  (and Google Colab would kick me out after 12 hrs)! I wonder the results reported in your paper is based on how many epochs?

Do you have recommendations for a lower epoch # that would reproduce the same results?

**Comment by morningmoni** [comment]
Please see the discussions above. 1000 is just a hypothetical number. You may first try 20~30 epochs.
