### ISSUE TITLE
What is the training preprocess data for WordNet only/WordNet +SemEval

### ISSUE THREAD

**Issue by l6chen** [morningmoni/TaxoRL#9]
It makes me really confused when I try to do with the semEval .
For wordNet only,  I used valname = dev_wnbo_hyper, model_prefix_file = 3in1_subseqFeat
For wordNet+SemEval, I used valname = dev_twodatasets, model_prefix_file = twodatasets_subseqFeat.
Am I doing right? 
By the way, why is dev_twodatasets so big compared to dev_wnbo_hyper. And how do you generate it?

**Comment by morningmoni** [comment]
I think you are. Because SemEval taxonomies are larger (n^2 pairs).
